_target_: src.models.fdvarnet_module.FDVarNetLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-4

scheduler:
  _target_: src.utils.tools.GradualWarmupScheduler
  _partial_: true
  multiplier: 1
  total_epoch: 5

after_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 45
  verbose: true

net:
  _target_: src.models.components.fdvarnet.Model_4DVarNN_GradFP
  mod_AE:
    _target_: src.models.components.nv_fourcastnet.FourCastNet
    img_size: [32, 64]
    patch_size: [4, 4]
    in_chans: 1
    out_chans: 1
    embed_dim: 64
    depth: 12
    mlp_ratio: 4.
    drop_rate: 0.
    drop_path_rate: 0.
    double_skip: true
    num_blocks: 8
    sparsity_threshold: 0.01
    hard_thresholding_fraction: 1.0
  ShapeData: [1, 32, 64]
  NiterProjection: 0
  NiterGrad: 5
  GradType: 1
  OptimType: 2
  InterpFlag: False
  periodicBnd: False

loss: null
eval_loss:
  _target_: src.utils.tools.WeightedMSELoss
  data_dir: ${paths.data_dir}

alpha: [1.0, 10]
ckpt: ${paths.pretrain_dir}/fourcastnet_5.625deg_leadtime6h.ckpt
