_target_: src.models.fdvargan_module.CycleGANLitModule

g_A2B:
  _target_: src.models.components.solver.Solver_4DVarGAN
  phi_r:
    _target_: src.models.components.nv_fourcastnet.FourCastNet
    img_size: [32, 64]
    patch_size: [4, 4]
    in_chans: 1
    out_chans: 1
    embed_dim: 64
    depth: 12
    mlp_ratio: 4.
    drop_rate: 0.
    drop_path_rate: 0.
    double_skip: true
    num_blocks: 8
    sparsity_threshold: 0.01
    hard_thresholding_fraction: 1.0
  mod_H:
    _target_: src.models.components.solver.Model_H
    shape_data: [1]
  m_GAN:
    _target_: src.models.components.resnet.Generator
    in_channels: 5
    hidden_channels: 32
    out_channels: 1
    num_downsampling: 2
    num_resnet_blocks: 4
    init_type: 'normal'
    init_gain: 0.02
  m_NormObs: 'l2'
  m_NormPhi: 'l2'
  shape_data: [1, 32, 64]

g_B2A:
  _target_: src.models.components.resnet.Generator
  in_channels: 1
  hidden_channels: 32
  out_channels: 1
  num_downsampling: 2
  num_resnet_blocks: 4
  init_type: 'normal'
  init_gain: 0.02

d_A:
  _target_: src.models.components.discriminators.PatchDiscriminator
  in_channels: 1
  out_channels: 32
  num_layers: 3
  init_type: normal
  init_gain: 0.02

d_B:
  _target_: src.models.components.discriminators.PatchDiscriminator
  in_channels: 3
  out_channels: 32
  num_layers: 3
  init_type: normal
  init_gain: 0.02

g_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-4
  betas: [0.5, 0.999]

d_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 2.5e-3
  betas: [0.5, 0.999]

scheduler:
  _target_: src.utils.tools.GradualWarmupScheduler
  _partial_: true
  multiplier: 1
  total_epoch: 5

after_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 45
  verbose: true

rec_loss:
  _target_: src.utils.tools.WeightedMSELoss
  data_dir: ${paths.data_dir}

loss:
  _target_: src.utils.tools.WeightedCycleGANLoss
  data_dir: ${paths.data_dir}
  loss_type: MSE
  rec_loss:
    _target_: src.utils.tools.WeightedMAELoss
    data_dir: ${paths.data_dir}
  lambda_cyc: 10
  lambda_idt: 10
  lambda_mse: 1.0
  lambda_adv: 1

# loss:
#   _target_: src.utils.tools.CycleGANLoss
#   loss_type: MSE
#   rec_loss: 
#     _target_: torch.nn.L1Loss
#   lambda_cyc: 10
#   lambda_idt: 10
#   lambda_mse: 1.0
#   lambda_adv: 1

lambda_4dvar: 60

ckpt: ${paths.pretrain_dir}/fourcastnet_5.625deg_leadtime6h.ckpt