# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
era5_dir: /tmp/dataset/era5/temperature_850_5.625deg
background_dir: /tmp/dataset/background/temperature_850_5.625deg
obs_dir: /tmp/dataset/obs/temperature_850_5.625deg
obs_mask_dir: /tmp/dataset/obs_mask
ckpt_dir: /tmp/dataset/ckpt

# path to logging directory
log_dir: /tmp/output

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: /tmp/output