# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: /dataset/era5/era5
xb_dir: /dataset/background_dtmodel6_predlen120/background_dtmodel6_predlen120
obs_dir: /dataset/observation_err0.015/observation_err0.015
obs_partial_mask_dir: /dataset/obs_partial_mask/obs_partial_mask
pretrain_dir: /dataset/pred_model/pred_model

# path to logging directory
log_dir: /model

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: /model

# path to working directory
work_dir: ${hydra:runtime.cwd}
