_target_: src.datamodules.assimilate.ncdatamodule.AssimDataModule
var: "temperature_850"
era5_dir: ${paths.era5_dir}
background_dir: ${paths.background_dir}
obs_dir: ${paths.obs_dir}
obs_mask_dir: ${paths.obs_mask_dir}
init_time: -48
obs_partial: 0.2
seed: 1024
batch_size: 512
num_workers: 8
pin_memory: true
prefetch_factor: 4
pred_len: 0
random_erase: True