_target_: src.datamodules.z500_datamodule.Z500DataModule
data_dir: ${paths.data_dir}
batch_size: 512
num_workers: 8
pin_memory: True
prefetch_factor: 4
continuous: True
lead_time: [3, 6, 12, 24, 72, 120]